CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';

CREATE USER IF NOT EXISTS 'inception_admin'@'%' IDENTIFIED BY 'SecurePass_123';
GRANT ALL PRIVILEGES ON *.* TO 'inception_admin'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
