CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE USER IF NOT EXISTS $MYSQL_USER@'localhost' IDENTIFIED BY "$(MYSQL_PASSWORD)";
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO $MYSQL_USER@'%' IDENTIFIED BY "$(MYSQL_PASSWORD)";
SET PASSWORD FOR 'root'@'localhost' = PASSWORD("$MYSQL_ROOT_PASSWORD");
FLUSH PRIVILEGES;
